In [2]:
import pandas as pd
import numpy as np
import os
pd.options.display.max_seq_items=10000
'''

1- creating a list of file names 
2- Open file_final in write mode
3- merge the context of the files 
4 write the results in the file_final
5- delete all the files
'''

files_dir="../data/RF/"
# Creating a list of filenames
file_list=os.listdir("../data/RF/")
file_list=[file for file in file_list if (len(file.split('.'))>1) and file.split('.')[1]=='csv' ]


# Open file_final in write mode
with open('RF_results.csv', 'w') as outfile:
    outfile.write('file_num,bootstrap,max_depth,max_features,min_samples_leaf,min_samples_split,n_estimators,criterion,roc_auc, F1,recall,precision')
    outfile.write("\n")
    # Iterate through list
    for names in file_list:

        # Open each file in read mode
        with open(files_dir+names) as infile:
#             print(names.split('.')[0]+','+infile.read())
            # read the data from file1 and
            # file2 and write it in file3
            outfile.write(names.split('.')[0]+','+infile.read())


        # Add '\n' to enter data of file2
        # from next line
        outfile.write("\n")

f=pd.read_csv('RF_results.csv')

In [11]:
f[(f['roc_auc']>0.44) & (f['recall']>0.5)].sort_values('recall', ascending=False)

,file_num,bootstrap,max_depth,max_features,min_samples_leaf,min_samples_split,n_estimators,criterion,roc_auc,F1,recall,precision
1,223,True,10,log2,8,10,1000,entropy,0.833,0.111,0.758,0.060
3623,413,True,10,log2,8,5,2000,entropy,0.833,0.112,0.758,0.060
1635,242,True,10,log2,8,5,1200,entropy,0.833,0.111,0.758,0.060
698,387,True,10,log2,8,10,1200,entropy,0.833,0.111,0.758,0.060
113,419,True,10,log2,8,10,800,entropy,0.834,0.112,0.758,0.060
...,...,...,...,...,...,...,...,...,...,...,...,...
3975,66,True,10,sqrt,2,10,1600,entropy,0.814,0.111,0.714,0.060
3344,61,True,10,sqrt,2,10,1000,entropy,0.815,0.112,0.714,0.061
3058,106,True,10,sqrt,2,10,2000,entropy,0.812,0.112,0.709,0.061
909,3,True,10,sqrt,1,2,600,entropy,0.812,0.112,0.709,0.061
738,1,True,10,sqrt,1,2,400,entropy,0.812,0.112,0.709,0.061