In [1]:
import pandas as pd
import numpy as np
import os


'''

1- creating a list of file names 
2- Open file_final in write mode
3- merge the context of the files 
4 write the results in the file_final
5- delete all the files
'''

files_dir="../data/RF/"
# Creating a list of filenames
file_list=os.listdir("../data/RF/")
file_list=[file for file in file_list if (len(file.split('.'))>1) and file.split('.')[1]=='csv' ]


# Open file_final in write mode
with open('RF_results.csv', 'w') as outfile:
    outfile.write('file_num,bootstrap,max_depth,max_features,min_samples_leaf,min_samples_split,n_estimators,criterion,roc_auc, F1,recall,precision')
    outfile.write("\n")
    # Iterate through list
    for names in file_list:

        # Open each file in read mode
        with open(files_dir+names) as infile:
#             print(names.split('.')[0]+','+infile.read())
            # read the data from file1 and
            # file2 and write it in file3
            outfile.write(names.split('.')[0]+','+infile.read())


        # Add '\n' to enter data of file2
        # from next line
        outfile.write("\n")

pd.options.display.max_seq_items=10000
f=pd.read_csv('RF_results.csv')

In [9]:
f[(f['roc_auc']>0.6) & (f['recall']>0.6)].sort_values('recall', ascending=False)

,file_num,bootstrap,max_depth,max_features,min_samples_leaf,min_samples_split,n_estimators,criterion,roc_auc,F1,recall,precision
4208,400,True,10,log2,8,5,800,entropy,0.785,0.059,0.648,0.031
1,223,True,10,log2,8,10,1000,entropy,0.779,0.058,0.637,0.030
1363,269,True,10,log2,8,10,2000,entropy,0.779,0.057,0.637,0.030
698,387,True,10,log2,8,10,1200,entropy,0.779,0.058,0.637,0.030
722,378,True,10,log2,8,10,2000,entropy,0.779,0.058,0.637,0.030
...,...,...,...,...,...,...,...,...,...,...,...,...
2974,272,True,10,log2,2,10,600,entropy,0.763,0.055,0.604,0.029
3235,271,True,10,log2,2,10,2000,entropy,0.763,0.055,0.604,0.029
3249,259,True,10,log2,8,10,1000,entropy,0.763,0.055,0.604,0.029
3352,376,True,10,log2,4,10,2000,entropy,0.763,0.055,0.604,0.029
2153,287,True,10,log2,2,10,2000,entropy,0.763,0.055,0.604,0.029