In [1]:
import pandas as pd
import numpy as np
import os

In [2]:

'''

1- creating a list of file names 
2- Open file_final in write mode
3- merge the context of the files 
4 write the results in the file_final
5- delete all the files
'''

files_dir="../data/RF/"
# Creating a list of filenames
file_list=os.listdir("../data/RF/")
file_list=[file for file in file_list if (len(file.split('.'))>1) and file.split('.')[1]=='csv' ]


# Open file_final in write mode
with open('RF_results.csv', 'w') as outfile:
    outfile.write('file_num,bootstrap,max_depth,max_features,min_samples_leaf,min_samples_split,n_estimators,criterion,roc_auc, F1,recall,precision')
    outfile.write("\n")
    # Iterate through list
    for names in file_list:

        # Open each file in read mode
        with open(files_dir+names) as infile:
#             print(names.split('.')[0]+','+infile.read())
            # read the data from file1 and
            # file2 and write it in file3
            outfile.write(names.split('.')[0]+','+infile.read())


        # Add '\n' to enter data of file2
        # from next line
        outfile.write("\n")

# for file in file_list:
#     os.remove(files_dir+file)

In [3]:
pd.options.display.max_seq_items=10000

In [4]:
f=pd.read_csv('RF_results.csv')

In [5]:
f

,file_num,bootstrap,max_depth,max_features,min_samples_leaf,min_samples_split,n_estimators,criterion,roc_auc,F1,recall,precision
0,545,True,10,log2,4,10,800,entropy,0.871,0.254,0.840,0.150
1,223,True,10,sqrt,8,10,1000,entropy,0.874,0.261,0.845,0.155
2,4817,True,80,sqrt,2,10,1400,entropy,0.640,0.392,0.284,0.632
3,4803,True,80,sqrt,8,10,1800,entropy,0.775,0.439,0.571,0.356
4,237,True,10,sqrt,8,5,600,entropy,0.874,0.263,0.843,0.155
...,...,...,...,...,...,...,...,...,...,...,...,...
6475,3813,True,60,log2,4,5,1800,entropy,0.728,0.454,0.468,0.441
6476,548,True,10,log2,4,10,1200,entropy,0.871,0.255,0.840,0.150
6477,1962,True,40,log2,8,5,2000,entropy,0.780,0.407,0.587,0.311
6478,1976,True,40,log2,8,5,1800,entropy,0.780,0.408,0.587,0.312
6479,3807,True,60,log2,4,5,1200,entropy,0.728,0.457,0.468,0.446

In [26]:
f[(f['roc_auc']>0.86) & (f['recall']>0.85) & (f['precision']>0.1)]

,file_num,bootstrap,max_depth,max_features,min_samples_leaf,min_samples_split,n_estimators,criterion,roc_auc,F1,recall,precision
157,425,True,10,sqrt,8,10,1400,entropy,0.878,0.265,0.851,0.157
238,418,True,10,sqrt,8,10,800,entropy,0.878,0.264,0.851,0.156
305,168,True,10,auto,8,10,1000,entropy,0.877,0.263,0.851,0.156
1005,351,True,10,sqrt,4,5,1200,entropy,0.878,0.265,0.851,0.157
1112,1,True,10,auto,1,2,400,entropy,0.878,0.265,0.851,0.157
1418,420,True,10,sqrt,8,10,1000,entropy,0.878,0.264,0.851,0.156
1762,122,True,10,auto,4,10,1800,entropy,0.878,0.264,0.851,0.156
2169,135,True,10,auto,4,5,1200,entropy,0.878,0.265,0.851,0.157
2349,108,True,10,auto,4,10,2000,entropy,0.878,0.266,0.851,0.157
2574,130,True,10,auto,4,5,800,entropy,0.878,0.266,0.851,0.157
2897,286,True,10,sqrt,2,10,2000,entropy,0.878,0.265,0.851,0.157
3069,481,True,10,log2,8,10,1600,entropy,0.875,0.255,0.851,0.150
4873,216,True,10,sqrt,8,10,2000,entropy,0.878,0.264,0.851,0.156
5371,611,True,10,log2,8,10,2000,entropy,0.876,0.256,0.851,0.151
5656,228,True,10,sqrt,8,10,1600,entropy,0.877,0.262,0.851,0.155
6080,239,True,10,sqrt,8,5,800,entropy,0.878,0.263,0.853,0.156
6092,207,True,10,auto,8,10,1200,entropy,0.878,0.264,0.851,0.156
6261,398,True,10,sqrt,8,5,600,entropy,0.877,0.262,0.851,0.155
6304,399,True,10,sqrt,8,5,600,entropy,0.880,0.264,0.855,0.156
6371,164,True,10,auto,8,10,600,entropy,0.878,0.265,0.851,0.157
6383,170,True,10,auto,8,10,1200,entropy,0.878,0.264,0.851,0.157

In [22]:
f[ (f['precision']>0.65)]

,file_num,bootstrap,max_depth,max_features,min_samples_leaf,min_samples_split,n_estimators,criterion,roc_auc,F1,recall,precision
1100,3560,True,60,sqrt,2,10,1800,entropy,0.644,0.402,0.290,0.651
1295,5503,True,90,sqrt,2,10,1600,entropy,0.644,0.402,0.290,0.651
3417,3519,True,60,sqrt,2,10,1200,entropy,0.639,0.392,0.280,0.652
4868,4188,True,70,sqrt,2,5,1600,entropy,0.644,0.402,0.290,0.651
4982,3552,True,60,sqrt,2,10,1000,entropy,0.641,0.397,0.284,0.656