In [2]:
import pandas as pd
import numpy as np
import os
pd.options.display.max_seq_items=10000
'''

1- creating a list of file names 
2- Open file_final in write mode
3- merge the context of the files 
4 write the results in the file_final
5- delete all the files
'''

files_dir="../data/RF/"
# Creating a list of filenames
file_list=os.listdir("../data/RF/")
file_list=[file for file in file_list if (len(file.split('.'))>1) and file.split('.')[1]=='csv' ]


# Open file_final in write mode
with open('RF_results.csv', 'w') as outfile:
    outfile.write('file_num,bootstrap,max_depth,max_features,min_samples_leaf,min_samples_split,n_estimators,criterion,roc_auc, F1,recall,precision')
    outfile.write("\n")
    # Iterate through list
    for names in file_list:

        # Open each file in read mode
        with open(files_dir+names) as infile:
#             print(names.split('.')[0]+','+infile.read())
            # read the data from file1 and
            # file2 and write it in file3
            outfile.write(names.split('.')[0]+','+infile.read())


        # Add '\n' to enter data of file2
        # from next line
        outfile.write("\n")
        
# read the file 
f=pd.read_csv('RF_results.csv')

In [8]:
f[(f['roc_auc']>0.86) & (f['recall']>0.85)].sort_values('recall', ascending=False)

,file_num,bootstrap,max_depth,max_features,min_samples_leaf,min_samples_split,n_estimators,criterion,roc_auc,F1,recall,precision
3939,417,True,10,log2,8,10,600,entropy,0.881,0.211,0.865,0.120
4124,165,True,10,sqrt,8,10,600,entropy,0.882,0.215,0.865,0.123
647,184,True,10,sqrt,8,5,800,entropy,0.882,0.215,0.865,0.123
4256,170,True,10,sqrt,8,10,1200,entropy,0.882,0.215,0.865,0.123
3867,199,True,10,sqrt,8,10,2000,entropy,0.883,0.217,0.865,0.124
...,...,...,...,...,...,...,...,...,...,...,...,...
3418,60,True,10,sqrt,2,10,1000,entropy,0.876,0.214,0.852,0.122
744,53,True,10,sqrt,1,10,2000,entropy,0.877,0.216,0.852,0.123
4053,239,True,10,log2,8,5,800,entropy,0.875,0.210,0.852,0.120
1031,151,True,10,sqrt,4,10,1000,entropy,0.876,0.214,0.852,0.123
1355,282,True,10,log2,2,10,1600,entropy,0.875,0.210,0.852,0.120