In [17]:
import pandas as pd
import numpy as np
import os
pd.options.display.max_seq_items=10000
'''

1- creating a list of file names 
2- Open file_final in write mode
3- merge the context of the files 
4 write the results in the file_final
5- delete all the files
'''

files_dir="../data/RF/"
# Creating a list of filenames
file_list=os.listdir("../data/RF/")
file_list=[file for file in file_list if (len(file.split('.'))>1) and file.split('.')[1]=='csv' ]


# Open file_final in write mode
with open('RF_results.csv', 'w') as outfile:
    outfile.write('file_num,bootstrap,max_depth,max_features,min_samples_leaf,min_samples_split,n_estimators,criterion,roc_auc, F1,recall,precision')
    outfile.write("\n")
    # Iterate through list
    for names in file_list:

        # Open each file in read mode
        with open(files_dir+names) as infile:
#             print(names.split('.')[0]+','+infile.read())
            # read the data from file1 and
            # file2 and write it in file3
            outfile.write(names.split('.')[0]+','+infile.read())


        # Add '\n' to enter data of file2
        # from next line
        outfile.write("\n")
      
f=pd.read_csv('RF_results.csv')

In [23]:
f[(f['roc_auc']>0.80) & (f['recall']>0.80)].sort_values('roc_auc', ascending=False)

,file_num,bootstrap,max_depth,max_features,min_samples_leaf,min_samples_split,n_estimators,criterion,roc_auc,F1,recall,precision
4124,165,True,10,sqrt,8,10,600,entropy,0.878,0.238,0.844,0.139
190,197,True,10,sqrt,8,5,2000,entropy,0.877,0.238,0.841,0.139
449,56,True,10,sqrt,2,10,600,entropy,0.877,0.237,0.841,0.138
2906,110,True,10,sqrt,4,10,600,entropy,0.877,0.238,0.841,0.138
3714,162,True,10,sqrt,8,10,2000,entropy,0.877,0.239,0.841,0.139
...,...,...,...,...,...,...,...,...,...,...,...,...
2142,293,True,10,log2,2,5,800,entropy,0.867,0.225,0.826,0.130
738,1,True,10,sqrt,1,2,400,entropy,0.867,0.235,0.821,0.137
385,368,True,10,log2,4,10,1200,entropy,0.867,0.223,0.828,0.129
2733,298,True,10,log2,2,5,1400,entropy,0.867,0.223,0.828,0.129
3667,348,True,10,log2,4,5,1000,entropy,0.867,0.222,0.828,0.128